export const coffeeRecipes = [
  {
    name: "Golden Jaggery Velvet",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Golden Cream",
    remarks: "Fixed Menu",
    image: "/images/products/Golden Jaggery Velvet.png"
  },
  {
    name: "Ice Mocha",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "-",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Classic Cold Brew",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Ice Cubes",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Vanilla Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Vanilla Syrup",
    remarks: "",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Caramel Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Salted Caramel",
    remarks: "",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Cinnamon Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Cinnamon",
    remarks: "Fixed Menu",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Honey Coffee",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Honey Drizzle",
    remarks: "Incompatible",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Cold Brew Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "70 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy",
    milkQty: "160 gm",
    topping: "-",
    remarks: "Practical DIY",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Cinnamon",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Cinnamon",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Honey Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Honey Drizzle",
    remarks: "",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Oat Salted Caramel Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Salted Caramel",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Oat Mocha",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Chocolate Drizzle",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Oat Vanilla",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Vanilla Syrup",
    remarks: "",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Oat Coconut Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "-",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Almond Mocha",
    concentrateType: "Coffee 50:50",
    concentrateQty: "70 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "160 gm",
    topping: "Almond Flakes",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Oat Nutmeg Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Nutmeg Powder",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Brown Sugar",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "-",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Chocolate Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "Cacao Powder",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Oat Hazelnut Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Oat Milk",
    milkQty: "170 gm",
    topping: "-",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Cold Brew Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "70 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Coconut Milk",
    milkQty: "160 gm",
    topping: "Coconut Flakes",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Salted Caramel",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Coconut Milk",
    milkQty: "170 gm",
    topping: "Salted Caramel",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Coconut Cinnamon Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Coconut Milk",
    milkQty: "170 gm",
    topping: "Cinnamon Powder",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Mocha Frappe",
    concentrateType: "Coffee 50:50",
    concentrateQty: "65 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Coconut Milk",
    milkQty: "165 gm",
    topping: "Rainbow Sprinkles",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Coconut Maple Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "20 gm",
    milkType: "Coconut Milk",
    milkQty: "170 gm",
    topping: "Maple Drizzle",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Jaggery Spice Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Cinnamon",
    remarks: "",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Jaggery Brown Sugar Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Brown Sugar Dust",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Jaggery Salted Caramel",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Salted Caramel",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Jaggery Almond Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Almond Flakes",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Jaggery Cold Brew Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "70 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "160 gm",
    topping: "-",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Jaggery Honey Spice Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Honey Drizzle",
    remarks: "",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Jaggery Coconut Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Coconut Flakes",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Jaggery Nutmeg Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Nutmeg Powder",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Jaggery Vanilla Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 gm",
    milkType: "Dairy",
    milkQty: "170 gm",
    topping: "Vanilla Syrup",
    remarks: "",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Oat Vanilla Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "175 gm",
    topping: "Vanilla Syrup",
    remarks: "",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Oat Caramel Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "175 gm",
    topping: "Salted Caramel",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Oat Cold Brew Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "70 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "165 gm",
    topping: "Cinnamon Cacao Powder",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Almond Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "175 gm",
    topping: "Almond Flakes",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Brown Sugar Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "175 gm",
    topping: "Brown Sugar Dust",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Oat Lavender Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "175 gm",
    topping: "Lavender Syrup",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Oat Nutmeg Latte (Jaggery)",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Oat Milk",
    milkQty: "175 gm",
    topping: "Nutmeg Powder",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Vanilla Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "155 gm",
    topping: "Vanilla Syrup",
    remarks: "",
    image: "/images/products/Ice Latte.png"
  },
  {
    name: "Coconut Salted Caramel Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "155 gm",
    topping: "Salted Caramel",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Coconut Mocha Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "70 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "165 gm",
    topping: "Cinnamon Cacao Powder",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Coconut Almond Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "60 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Almond Flakes",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Brown Sugar Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Brown Sugar Dust",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Coconut Lavender Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Lavender Syrup",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Nutmeg Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Nutmeg Powder",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Cinnamon Latte (Coconut)",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Cinnamon",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Flakes Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Coconut Flakes",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Coconut Honey Latte",
    concentrateType: "Coffee 50:50",
    concentrateQty: "80 gm",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 gm",
    milkType: "Coconut Milk",
    milkQty: "175 gm",
    topping: "Honey Drizzle",
    remarks: "",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Hazelnut Cream Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "80 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy Milk",
    milkQty: "175 gm",
    topping: "Hazelnut Syrup",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Choco Almond Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "70 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy Milk",
    milkQty: "180 gm",
    topping: "Cocoa Powder Almond Flakes",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Honey Nut Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "80 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "12 gm",
    milkType: "Dairy Milk",
    milkQty: "175 gm",
    topping: "Honey Nutmeg",
    remarks: "",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Mango Cold Brew",
    concentrateType: "Coffee 70-30",
    concentrateQty: "75 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy Milk",
    milkQty: "180 gm",
    topping: "Mango Pulp",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Honey Almond",
    concentrateType: "Coffee 70-30",
    concentrateQty: "80 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "12 gm",
    milkType: "Dairy Milk",
    milkQty: "175 gm",
    topping: "Honey Almond",
    remarks: "",
    image: "/images/products/Honey Spiced Latte.png"
  },
  {
    name: "Strawberry Cream Coffee",
    concentrateType: "Coffee 70-30",
    concentrateQty: "75 gm",
    sweetener: "Sugar Syrup",
    sweetenerQty: "15 gm",
    milkType: "Dairy Milk",
    milkQty: "180 gm",
    topping: "Strawberry Crush",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Sweet Cream Cold Brew",
    concentrateType: "Coffee 70-30",
    concentrateQty: "60 ml",
    sweetener: "Sugar Syrup",
    sweetenerQty: "25 ml",
    milkType: "Dairy Milk",
    milkQty: "160 ml",
    topping: "Thick Milk Foam",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Desi Jaggery Coffee",
    concentrateType: "Coffee 70-30",
    concentrateQty: "60 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 ml",
    milkType: "Dairy Milk",
    milkQty: "170 ml",
    topping: "Elaichi Pinch",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Jaggery Mocha",
    concentrateType: "Coffee 70-30",
    concentrateQty: "50 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "15 ml",
    milkType: "Dairy Milk",
    milkQty: "165 ml",
    topping: "Chocolate Syrup 10 ml",
    remarks: "",
    image: "/images/products/Ice Mocha.png"
  },
  {
    name: "Smoky Jaggery Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "55 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 ml",
    milkType: "Dairy Milk",
    milkQty: "165 ml",
    topping: "Cocoa Cinnamon",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Creamy Jaggery Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "50 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 ml",
    milkType: "Dairy Milk",
    milkQty: "150 ml",
    topping: "20 ml Fresh Cream",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Almond Jaggery Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "60 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 ml",
    milkType: "Dairy Milk",
    milkQty: "165 ml",
    topping: "Almond Cashew Crush",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  },
  {
    name: "Spiced Coffee",
    concentrateType: "Coffee 70-30",
    concentrateQty: "45 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 ml",
    milkType: "Dairy Milk",
    milkQty: "170 ml",
    topping: "Cinnamon Nutmeg",
    remarks: "",
    image: "/images/products/cold-brew.png"
  },
  {
    name: "Jaggery Cocoa Latte",
    concentrateType: "Coffee 70-30",
    concentrateQty: "45 ml",
    sweetener: "Jaggery Syrup",
    sweetenerQty: "20 ml",
    milkType: "Dairy Milk",
    milkQty: "170 ml",
    topping: "Cocoa Powder Sprinkle",
    remarks: "",
    image: "/images/products/Salted Caramel Jaggery.png"
  }
];

export const normalize = (value) =>
  String(value || "")
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ");

export const drinkImageMap = {};
coffeeRecipes.forEach(recipe => {
  drinkImageMap[normalize(recipe.name)] = recipe.image;
});
